### ISSUE TITLE
"Route planen" möchte rückwärts planen nach erstem Ladepunkt

### ISSUE THREAD

**Issue by KevinKickass** [Urkman/eCar#1]
Wenn ich eine Route von "Velbert" nach "Dresden" planen möchte, kann ich den ersten Ladepunkt ohne Probleme auswählen und einfügen.
Ladepunkt 1 (Autobahnraststätte Am Biggenkopf Süd, Diemelstadt A44)

Nachdem ich diesen dann eingefügt habe möchte er zurück planen und das nicht nur einen Ladepunkt zurück, sondern unbegrenzt viele.
Rein von der in den Einstellungen eingestellten Reichweite von 180km für die erste Etappe sollte der Ladepunkt 1 aber kein Problem sein.

Wenn ich nun einen 2. Ladepunkt zwischen Start und dem oben genannten 1. Ladepunkt wähle, ihn als Ladepunkt 2 einfüge, den 1. Ladepunkt wieder lösche, kann ich ohne Probleme die Route von dem Punkt aus fertig planen und hinterher den Punkt einfach wieder rauslöschen.

Einstellungen:
Erste Etappe 180
Weitere Etappen 130
Vor dem Stopp 100

Konnte man mir folgen?

Bei Fragen stehe ich selbst verständlich zur Verfügung!

![img_1979](https://user-images.githubusercontent.com/45273132/48921794-7764af80-eea2-11e8-8501-656e9bea452e.PNG)
![img_1980](https://user-images.githubusercontent.com/45273132/48921795-7764af80-eea2-11e8-89eb-2a01850b6f74.PNG)
![img_1981](https://user-images.githubusercontent.com/45273132/48921796-7764af80-eea2-11e8-975d-3e42f456e452.PNG)
![img_1982](https://user-images.githubusercontent.com/45273132/48921797-7764af80-eea2-11e8-94e7-fe77e9b76882.PNG)
![img_1983](https://user-images.githubusercontent.com/45273132/48921798-7764af80-eea2-11e8-9b5a-6860f4f8fabf.PNG)

MfG
EinKevin

**Comment by Urkman** [comment]
Das Problem ist, wenn die Strecke zum ersten Ladepunkt größer als 180km ist, versucht er natürlich noch einen Zwischenhalt einzufügen, da ja gesagt wurde Strecke max 180km...

**Comment by KevinKickass** [comment]
die war ja nicht weiter als 180km
das waren 163

und wenn ich dann einen zwischenpunkt ausgewählt habe sollte ich unbegrenzt viele weiter zwischenpunkte dort auswählen.


Von meinem iPhone gesendet

Am 23.11.2018 um 10:00 schrieb Stefan Sturm <notifications@github.com<mailto:notifications@github.com>>:


Das Problem ist, wenn die Strecke zum ersten Ladepunkt größer als 180km ist, versucht er natürlich noch einen Zwischenhalt einzufügen, da ja gesagt wurde Strecke max 180km...

**Comment by Urkman** [comment]
Ich werde mal eine Warnung einbauen, wenn eine Ladestation ausgewählt wird, die zu weit entfernt ist...

**Comment by Urkman** [comment]
Habe da in der Berechnung noch einen Fehler gefunden...
Bitte in Version 1.0.7 noch testen...

**Comment by KevinKickass** [comment]
Sieht nun gut aus! TOP! ;-)
