### ISSUE TITLE
Tippen eines Zusammenfassungs-Pins zeigt Liste der der Säulen

### ISSUE THREAD

**Issue by IPSCoyote** [Urkman/eCar#10]
Ist kein Issue, aber eher eine Geschmacksfrage.

Wenn man auf den Zusammenfassungs-Pin tippt, bekommt man eine kleine Liste der darin enthaltenen Säulen.

![img_5560](https://user-images.githubusercontent.com/33869299/49020977-f05d5300-f191-11e8-803b-22f9399149d1.png)

Ich bin mir unschlüssig ob ich dies hilfreich finde. Wenn ich die Säulen genau kenne, dann man das hilfreich sein. Ich nutze die App aber eher, um eine Säule zu finden wo ich mich nicht auskenne. Ich fände es da angenehmer, wenn die Karte den Pin auflösen würde und ich so auch gleich sehe, wo die Säulen selbst sind...

![img_5561](https://user-images.githubusercontent.com/33869299/49020895-c4da6880-f191-11e8-8843-7391029c2b5c.png)

Wie gesagt. Ist wohl Geschmacksache, wo ggf. auch mal andere ihre Meinung äußern sollten ;)

**Comment by IPSCoyote** [comment]
Nachtrag.
Ich möchte nach Mannheim fahren und will mal schauen, ob's da Säulen gibt. Wenn ich die Karte auf Mannheim positioniere, dann sehe ich zunächst einen Pin mit (26) Säulen. 

Wenn ich den antippe, dann sehe ich eine kleine Liste in der die 26 Säulen enthalten sind. 
![liste](https://user-images.githubusercontent.com/33869299/49022234-a45fdd80-f194-11e8-8039-678681d575d5.jpg)

Hier fände ich des deutlich angenehmer, die Karte würde weiter reinzoomen, gerne auch Stufenweise:
![zoomen](https://user-images.githubusercontent.com/33869299/49022243-a9249180-f194-11e8-8e0a-a50405faa72a.jpg)

**Comment by Urkman** [comment]
Versuch mal einen Doppeltap au den jeweiligen Sammelpin...

**Comment by IPSCoyote** [comment]
Geht durch Doppeltippen -> erledigt
