### ISSUE TITLE
1.2 (2) - Angaben zum Auto

### ISSUE THREAD

**Issue by IPSCoyote** [Urkman/eCar#12]
1. 1. Warum Bezeichnung, Hersteller und Typ? Wenn die Felder keine besonderen Funktionen haben, dann dürfte doch ein Feld reichen, oder?

2. Batterie, Ladeleistung, Verbrauch: Kommazahlen! Der eGolf hat 35.5kwh Kapazität und lädt an AC mit 7.4kw

3. Auto "hinzufügen" übernimmt die Daten des letzten/vorhandenen Fahrzeugs. Ist das sinnvoll? Zumindest irritierend

4. Zurück (nach Eingabe von Fahrzeugdaten) speichert die Änderungen nicht. Mag zwar richtig sein, ist aber ärgerlich. Warum nicht "Änderungen per se speichern".

5. "Meine Autos" werden in der Einstellungsübersicht nicht angezeigt (wie bei den anderen Daten)

**Comment by Urkman** [comment]
1.) Da bin ich ehrlich... ich würde gerne aus den angelegten Auto mal eine Liste erstellen und diese dann in der App zur Auswahl anbieten...

2.) ??? Das geht doch.

3.) Das ist ein Bug

4.) Und wie verwerfe ich dann fehlerhafte Eingaben?

5.) Das kommt noch :)

**Comment by IPSCoyote** [comment]
zu 1) Das wäre gut, aber auch da wirst du Lücken haben. Insofern würde ich eher eine Auswahlliste anbieten und zusätzlich eine Bezeichnung (man könnte ja auch 2x dasselbe eAuto fahren und es anlegen wollen (auch wenn's ja faktisch dann egal wäre ))

zu 2) iPhone X: Nein, kein Komma vorhanden, nur Ziffern

zu 4.) Überschreiben/entfernen/Neu Ändern. Wo findest du in den iPhone Einstellungen einen "Einstellungen speichern" Button? ;)

**Comment by Urkman** [comment]
zu 2.) Hast du mal einen Screenshot? Welche Sprache hast du eingestellt?

**Comment by Urkman** [comment]
2.) Fehler gefunden... Fix kommt später mit einer neuen Version...

**Comment by IPSCoyote** [comment]
Done
