### ISSUE TITLE
1.2 (2) - Tarife

### ISSUE THREAD

**Issue by IPSCoyote** [Urkman/eCar#13]
1. Kommazahlen! (z.B. 4,99€ im Monat); Preiseinheit benennen

2. Strafen: Eine "maximale Standdauer" gibt es nicht (da wohl eher vom Parkplatzbetreiber abhängig), wohl aber eine Strafe "nach X Minuten Ladendauer". Diese Strafe könnte zudem unterschiedlich, ob AC oder DC geladen wird, sein

3. Wenn "Angaben zum Tarif" oder "Strafen" übergreifend sind (unabhängig von "pro kW", "pro Minute", etc.), dann sollten diese Daten oberhalb der Untergruppen sein

**Comment by Urkman** [comment]
1.) Auch hier sollte das gehen...

2.) Das war mit "maximale Standdauer" gemeint ;) Das es da auch unterscheide zwischen AC und DC gibt, wusste ich nicht. Hast du da einen Anbieter als Beispiel?

3.) Hier ist "pro Tarif" nur eine Auswahl angedacht. Also nur "pro kW" oder "pro Minute"

**Comment by IPSCoyote** [comment]
zu 1) iPhone X... auch hier kein Komma als Eingabemöglichkeit

zu 2) Die Maingau-Karte hat zwar 10ct/min Strafe, aber bei AC ab 120min, bei DC ab 60min.

zu 3) Es gibt Tarife (Audi!), die haben monatlichen Grundpreis + Grundpreis je Ladevorgang (unterschiedlich an AC und DC und Ionity!) + Preis je kWh

**Comment by Urkman** [comment]
2.) OK, dann baue ich da noch eine Unterteilung ein.

3.) Dann muss bei "pro KW" und "pro Minute" noch ein optionaler Grundpreis für AC und DC erfasst werden können...

**Comment by IPSCoyote** [comment]
Ich fände es optisch auch schön, wenn man beim Preis in **einer** Zeile sowas hätte wie

![tarif](https://user-images.githubusercontent.com/33869299/52341386-b1aa0b80-2a12-11e9-911f-910412b8d188.jpg)

Fände ich leserlicher

**Comment by Urkman** [comment]
Gut Idee, aber 3 nebeneinander passt nicht. Es gibt ja auch noch iPhone 5s Nutzer ;)
Ich lasse mir da mal was einfallen... 

Aber die Eingaben werden weiter in Euro bleiben...

**Comment by Urkman** [comment]
Habe den View überarbeitet und steht in Version 1.2.3 zur Verfügung...

**Comment by IPSCoyote** [comment]
Done
