### ISSUE TITLE
Welcome Bildschirm

### ISSUE THREAD

**Issue by IPSCoyote** [Urkman/eCar#2]
Bzgl. der Einführung

- man kann nicht zurück blättern
- sollte vor- und zurück(!) swipen können (wischen)
- Ein paar Schreibfehler sind auch drauf (z.B. zusammengeschriebene Wörter wie "Sokannst", Großschreibung, Komma,...).

**Comment by Urkman** [comment]
Swipe baue ich wieder ein...
Die Texte sind nicht final und einfach nur "schnell" was hingeschrieben ;)

**Comment by Urkman** [comment]
Swipe ist in Version 1.0.7 eingebaut...
