### ISSUE TITLE
Zieleingabe im Routenplaner lässt die App abstürzen

### ISSUE THREAD

**Issue by IPSCoyote** [Urkman/eCar#3]
iPhone X, eCar Version 1.0 (6)

Wenn ich auf den Routenplaner gehe und auf den Start oder das Ziel tippe stürzt die App ab.

**Comment by rolfrenz** [comment]
Ditto bei mir mit iPhone SE und iPad

**Comment by Urkman** [comment]
Oh ja... Mache heute noch eine neue Version :)

**Comment by Urkman** [comment]
Ist in Version 1.0.7 gefixt...
