### ISSUE TITLE
Zoomstufe beim Auswählen einer Ladesäule aus der Liste zu gering

### ISSUE THREAD

**Issue by IPSCoyote** [Urkman/eCar#4]
Durch das tolle "Pins zusammenfassen" Feature (top) passiert es, das man, wenn man eine Säule aus der Liste wählte, nur "Summenpins" sieht und die Säule selbst noch gar nicht sichtbar ist. Hier sollte also mehr gezoomt werden (zumindest soweit, das die Säule erkennbar ist), da man so die Säule selbst nicht markieren und keine Details sehen kann. 

Wenn man dann selbst weiter rein zoomt (und die Pin-Zusammenfassung auflöst) ist die zuvor gewählte Säule nicht markiert. Bei mehreren weiß man dann nicht, welche es war. Selektiert man dann (nach dem manuellen zoomen) die Säule erneut aus der Liste, wird wieder rausgezommt (und die "Summenpins" erscheinen wieder).

**Comment by Urkman** [comment]
Wie wäre es denn, wenn die "Fahne" des Pis über dem Sammelpin angezeigt wird?

**Comment by IPSCoyote** [comment]
Übereinander finde ich immer unschön.

Zudem: Nehmen wir mal ein Stadtgebiet mit mehreren Säulen an. da wäre ein Pin über einem Kreis mit einer (4) doch auch unpraktisch. Da möchte man doch ggf. die gewählte Säule sehen, aber auch gleich die Nachbarsäulen, oder?

**Comment by IPSCoyote** [comment]
Nachtest Version 1.0 (7)

Es erscheint jetzt eine Sprechblase über den "Summenpin". 

Der Inhalt der Sprechblase ist wohl Zufall. Ich klicke eine Säule "Gemeindeverwaltung an", in der Sprechblase steht dann mal "Rathaus", mal "Gemeindeverwaltung", mal was anderes (wohl irgendein Text der zusammengefassten Säulen). 

Wenn man dann rein zoomt, wird die richtige Säule durch eine weitere Sprachblase mit den Details hervorgehoben. Dies allerdings nur, wenn man darauf zu zoomt. Zoomt man etwas daran vorbei, kommt keine Sprechblase. 
Wenn die Sprechblase erscheint, kann man diese Sprechblase aber nicht mehr schließen! Sie bleibt auch da, wenn man eine andere Säule markiert. 

Habe ein Video beigefügt.
[Zoom Problem.mp4.zip](https://github.com/Urkman/eCar/files/2611371/Zoom.Problem.mp4.zip)


Ich könnte mir für das Zoomverhalten auch folgende Lösung vorstellen:

1. Man selektiert eine Säule aus der Liste -> die Karte fokussiert auf die Säule
2. Sind mehrere Säulen an der Stelle wird der Kreis mit der Anzahl gezeigt in in einer Sprechblase steht der Name der ausgewählten Säule
3. Wenn man jetzt ein 2tes mal die Säule antippt (in der Liste, die Sprechblase oder den Summenpin), dann wird soweit gezoomt, das genau die gewählte Säule im Fokus ist mit dessen Detail-Sprechblase

**Comment by Urkman** [comment]
Ich habe in Version 1.0.8 mal in die Einstellungen einen Switch eingebaut.
Wenn der eingeschaltet ist, wird bei Auswahl einer Ladestation aus der Liste weiter reingezoomt.

**Comment by IPSCoyote** [comment]
Danke,

Gefällt mir besser. Die Liste kann man ja auf „Fullscreen“ oder 4 Einträge (auf dem X) „einrasten“. Könnte man dies auch bei 2 Einträgen machen, um mehr von der Karte zu sehen und trotzdem in der Liste selektieren zu können? Ist aber nicht Kriegsentscheidend.

Gruß
  Volkmar

**Comment by Urkman** [comment]
Hab das mal eingebaut. Kommt mit der nächsten Version...

**Comment by IPSCoyote** [comment]
(1.0.9) Sieht gut aus.

**Comment by Urkman** [comment]
In der Version 1.0.10 werden jetzt beim Klick auf einen Sammelpin alle darin befindlichen Ladestationen in einer Liste angezeigt.

Bitte mal anschauen.

**Comment by IPSCoyote** [comment]
Hi,

Bin mir nicht sicher, ob ich das hilfreich finde. Mir persönlich wäre ein reinzoomen wohl lieber. Aber das wäre nur meine Meinung.
Habe mal ein Ticket angelegt. Vielleicht äußert sich ja mal jemand anders dazu...

Gruß
  Volkmar
