### ISSUE TITLE
Liste zeigt nicht alle Säulen der Entfernung nach

### ISSUE THREAD

**Issue by IPSCoyote** [Urkman/eCar#6]
(1.0.9)

In der Liste werden nicht alle Säulen der Entfernung nach angezeigt. 

Wenn in der Karte Säulen via Pin zusammengefasst wurden, so wird nur die erste Säule einer Pin-Gruppe in der Liste angezeigt. Das macht aus meiner Sicht keinen Sinn.

Beispiel:
![img_5551](https://user-images.githubusercontent.com/33869299/48984160-8e044400-f0f8-11e8-82d5-b7dc5872b3f5.png)
Bei mir sind in der Nähe (Ort Bad Schönborn) 7 Säulen als Pin zusammengefasst, in Östringen 2. In der Liste ist aber nur eine dieser Säulen (die nächst-gelegene) aufgeführt! Es steht in der Liste eine Säule in Bad Schönborn, und dann als nächste Säule die Säule in Östringen. Dei 6 weiteren Säulen in Bad Schönborn, die näher liegen als Östringen, werden nicht aufgeführt.

![img_5552](https://user-images.githubusercontent.com/33869299/48984171-bab85b80-f0f8-11e8-98c4-61b43c5e43a0.png)
Auch nach dem manuellen Zoomen (oder dem anklicken einer Säule) werden nicht alle Säulen in der Liste angezeigt.

**Comment by Urkman** [comment]
Ich kann das hier bei mir aktuell nicht reproduzieren. 
Bei mit werden alle Ladestationen angezeigt, die unter einem "Sammelpin" versteckt sind.
Aber natürlich eventuell nicht alle direkt untereinander, wegen der "Luftlinien" Entfernung.

**Comment by IPSCoyote** [comment]
Hm. Du könntest Recht haben. Ist ggf. wieder mein Fehler, das ich die "Luftentfernung" mit der tatsächlich Entfernung (die man in seinem Umfeld natürlich eher im Kopf hat) durcheinander bringe.

Insofern schließe ich das erstmal.
