### ISSUE TITLE
Grafiken werden nicht korrekt dargestellt

### ISSUE THREAD

**Issue by IPSCoyote** [Urkman/eCar#7]
(1.0.9)

Nicht immer, aber es kommt vor, das Bilder nicht richtig dargestellt werden:

z.B: Säule Gemeindeverwaltung Bad Schönborn

![img_5557](https://user-images.githubusercontent.com/33869299/48984883-d7a55c80-f101-11e8-97aa-dd3c611ab3e0.png)
![img_5558](https://user-images.githubusercontent.com/33869299/48984884-da07b680-f101-11e8-8d02-d89728113695.png)

**Comment by Urkman** [comment]
Ist in Version 1.0.10 gefixt.

**Comment by IPSCoyote** [comment]
1.0.10

Jetzt ist die Aspect Ratio zwar korrekt, aber die Bilder "unterlaufen" teilweise die Bereichsbalken...

![img_5559](https://user-images.githubusercontent.com/33869299/49020352-842e1f80-f190-11e8-8de8-f9cbb91cf09f.png)

**Comment by Urkman** [comment]
Hoffentlich in 1.0.11 gefixt ;)

**Comment by IPSCoyote** [comment]
1.0.12: passt
