### ISSUE TITLE
Löschen von "Meine Karten" geht nicht

### ISSUE THREAD

**Issue by IPSCoyote** [Urkman/eCar#8]
(1.0.9)

Wenn man bei seinen Ladekarten auf Bearbeiten geht "der Bleistift rechts oben", kann man nur umsortieren, nicht löschen. Zudem bleibt der Bleistift oben (kein X oder OK oder dergl.).

![img_5553](https://user-images.githubusercontent.com/33869299/48984918-2f43c800-f102-11e8-9840-2f33d95aeaf1.png)

![img_5554](https://user-images.githubusercontent.com/33869299/48984920-3074f500-f102-11e8-9e5f-d96656f31303.png)

**Comment by Urkman** [comment]
Ist in Version 1.0.10 gefixt.
Dann können die Karten einfach durch Swipe gelöscht werden.
Der "Edit Modus" wird nur noch für das verschieden benötigt.

**Comment by IPSCoyote** [comment]
1.0.10: fixed
