### ISSUE TITLE
Auflistung "Meine Ladekarten" in Details falsch/unklar

### ISSUE THREAD

**Issue by IPSCoyote** [Urkman/eCar#9]
Die Auflistung von "Meine Ladekarten" in den Säulen-Details ist unklar. Ich finde die farbigen Punkte unklar. Zudem ist die Sortierung nicht entsprechend der gepflegten Sortierung.

![img_5555](https://user-images.githubusercontent.com/33869299/48984982-269fc180-f103-11e8-8f41-40c1020ffe94.png)

Ich fände eine klare Auflistung der Namen besser/informativer

**Comment by Urkman** [comment]
Ich habe mich hier für Farbpunkte entschieden, da diese Überall in der App angezeigt werden und so einen "Wiedererkennungswert" haben sollten :)

**Comment by IPSCoyote** [comment]
Ja, die Punkte finde ich im Grunde auch gut. Nur ist die Reihenfolge hier nicht die, die bei den Sprechblasen in der Karte verwendet wird. Die Reihenfolge sollte der Reihenfolge in den Einstellungen entsprechen. Deshalb ist es mir auch vornehmlich aufgefallen.

**Comment by Urkman** [comment]
Alles klar... Schaue ich mr an :)

**Comment by IPSCoyote** [comment]
OMG... wieso steht im Screenshot "Periodisierung"... sowas schreibt doch kein Mensch. Natürlich die Periodisierung oder Reihenfolge... ;)

**Comment by Urkman** [comment]
Ist in Version 1.0.10 gefixt

**Comment by IPSCoyote** [comment]
1.0.10: Reihenfolge gefixt
